### PR TITLE
Fixes #85 Support html-loader 1 and raw-loader 4

### LINKED ISSUE #85: Stopped working with html-loader v1.0.0
html-loader was updated to v1.0.0 with breaking changes. Since then ngtemplate-loader is breaking my build.

Everyone have the same issue?
Somebody have a fix for that?

### PR DESCRIPTION
**Pull request by WearyMonkey**
Makes content capture more robust by replacing the default export with a variable, and then using that variable. Instead of the crazy custom string parsing I was doing before.

### CODE REVIEW

**Comment by WearyMonkey** [comment]
@peterpoe @cb-eli @benochr  thanks for your feedback on #85 

Could you please test this version for me? I don't have a production angular 1 project anymore.

**Comment by benochr** [comment]
Hello @WearyMonkey 

Sorry for the delay in response. Been on holiday last week.

I can confirm that our problems are solved when using the version in this branch `toby-html-loader-1-fix`

When using the old version with html-loader version 1.1.0 we get following error when running our tests:
```
Chrome Headless 84.0.4147.0 (Mac OS 10.15.5) ERROR
  An error was thrown in afterAll
  Uncaught Error: Module parse failed: Unexpected token (3:0)
  File was processed with these loaders:
   * ./node_modules/ngtemplate-loader/index.js
   * ./node_modules/html-loader/dist/cjs.js
   * ./loaders/i18n-loader.js
  You may need an additional loader to handle the result of these loaders.
  | var path = 'dialogs/app.directive.html';
  | var html = // Module
  > var code = 
```

A similar error occurs when starting a local development server.

After updating `ngtemplate-loader` with this branch the errors are gone:
```
Chrome Headless 84.0.4147.0 (Mac OS 10.15.5): Executed 391 of 395 (skipped 4) SUCCESS (0.905 secs / 0.608 secs)
TOTAL: 391 SUCCESS
```

PS: I also checked this branch with the old version of `html-loader` we were using, version 0.5.5, and all works well. So it seems backward compatible.

**Comment by Ventajou** [comment]
@WearyMonkey any plans to merge and release this?

**Comment by WearyMonkey** [comment]
Sorry for the delay, I've released it now.

**Pull request merged**
